title: Anyhow...
theme: minima
author: W. Wesley Monroe
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The best part of getting lost in the digital world is ultimately finding your way through to the next level.

# social links
twitter_username: purpleHey
github_username:  purpleHey

show_excerpts: true # set to false to remove excerpts on the homepage
