title: Anyhow...
author: William Wesley Monroe
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Trying to make sense of a digital world.

# social links
twitter_username: @purpleHey
github_username:  purplehey

show_excerpts: true # set to false to remove excerpts on the homepage
